### ISSUE TITLE
Error in Hyprland 0.35

### ISSUE THREAD

**Issue by CRAG666** [shezdy/hyprsplit#1]
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━  4 / 5  Installing repositoryterminate called after throwing an instance of 'std::f
ilesystem::__cxx11::filesystem_error'
  what():  filesystem error: cannot copy file: No such file or directory [/tmp/hyprpm/new/hyprsplit.so] [/home/think-crag/.local/share/
hyprpm/hyprsplit/hyprsplit.so]
[1]    28319 IOT instruction (core dumped)  hyprpm add https://github.com/shezdy/hyprsplit

**Comment by CRAG666** [comment]
g++ -shared -fPIC --no-gnu-unique -Wall -g -DWLR_USE_UNSTABLE -std=c++23 -O2 `pkg-config --cflags pixman-1 libdrm hyprland` src/main.cpp -o hyprsplit.so
src/main.cpp: In function ‘std::string getWorkspaceOnCurrentMonitor(const std::string&)’:
src/main.cpp:10:136: error: ‘struct SConfigValue’ has no member named ‘getDataStaticPtr’
   10 | st NUMWORKSPACES = (Hyprlang::INT* const*)HyprlandAPI::getConfigValue(PHANDLE, "plugin:hyprsplit:num_workspaces")->getDataStaticPtr();
      |                                                                                                                    ^~~~~~~~~~~~~~~~

src/main.cpp: In function ‘void ensureGoodWorkspaces()’:
src/main.cpp:62:136: error: ‘struct SConfigValue’ has no member named ‘getDataStaticPtr’
   62 | st NUMWORKSPACES = (Hyprlang::INT* const*)HyprlandAPI::getConfigValue(PHANDLE, "plugin:hyprsplit:num_workspaces")->getDataStaticPtr();
      |                                                                                                                    ^~~~~~~~~~~~~~~~

src/main.cpp: In function ‘void focusWorkspace(std::string)’:
src/main.cpp:116:136: error: ‘struct SConfigValue’ has no member named ‘getDataStaticPtr’
  116 | st NUMWORKSPACES = (Hyprlang::INT* const*)HyprlandAPI::getConfigValue(PHANDLE, "plugin:hyprsplit:num_workspaces")->getDataStaticPtr();
      |                                                                                                                    ^~~~~~~~~~~~~~~~

src/main.cpp: In function ‘void grabRogueWindows(std::string)’:
src/main.cpp:191:136: error: ‘struct SConfigValue’ has no member named ‘getDataStaticPtr’
  191 | st NUMWORKSPACES = (Hyprlang::INT* const*)HyprlandAPI::getConfigValue(PHANDLE, "plugin:hyprsplit:num_workspaces")->getDataStaticPtr();
      |                                                                                                                    ^~~~~~~~~~~~~~~~

src/main.cpp: In function ‘PLUGIN_DESCRIPTION_INFO pluginInit(void*)’:
src/main.cpp:241:87: error: invalid initialization of reference of type ‘const SConfigValue&’ from expression of type ‘Hyprlang::INT’ {aka ‘long int’}
  241 |     HyprlandAPI::addConfigValue(PHANDLE, "plugin:hyprsplit:num_workspaces", Hyprlang::INT{10});
      |                                                                                       ^~~~~~~
En el fichero incluido desde src/globals.hpp:3,
                 desde src/main.cpp:1:
/usr/include/hyprland/src/plugins/PluginAPI.hpp:115:93: nota: in passing argument 3 of ‘bool HyprlandAPI::addConfigValue(void*, const std::string&, const SConfigValue&)’
  115 |     APICALL bool addConfigValue(HANDLE handle, const std::string& name, const SConfigValue& value);
      |                                                                         ~~~~~~~~~~~~~~~~~~~~^~~~~
make: *** [Makefile:7: all] Error 1

**Comment by shezdy** [comment]
the plugin requires hyprland version >=`v0.36.0`
