### ISSUE TITLE
Hyprland doesn't recognize hyprsplit's dispatchers even with hyprsplit enabled.

### ISSUE THREAD

**Issue by kubni** [shezdy/hyprsplit#11]
Hello. I wanted to try out this plugin, installed it using hyprpm, which shows it as enabled.
However, adding `split:workspace` instead of standard `workspace` makes Hyprland show a configuration error because of an invalid dispatcher.

Is there additional configuration I need to do in order for it to recognize hyprsplit's dispatchers?

**Comment by shezdy** [comment]
do you have `exec-once = hyprpm reload -n` in your config?

**Comment by kubni** [comment]
I didn't have that. I was reading the instructions on your Github page and completely forgot to read through the hyprpm manual. This was my first plugin ever that I installed using hyprpm so I was wondering why it didn't work.
Thanks! And thanks for this amazing plugin, it was practically the only thing that was stopping me from using Hyprland.
