### ISSUE TITLE
split:grabroguewindows grabs windows from special workspaces

### ISSUE THREAD

**Issue by AurelWeinhold** [shezdy/hyprsplit#12]
Hi, first of all, thank you for the plugin.

I have discovered a problem with the `split:grabroguewindows` dispatcher. It also grabs all windows on special workspaces, which, I think, it is not supposed to.

To reproduce open any window in a special workspace, then go to a "regular" workspace and activate the dispatcher (i.e. via a keybinding).

**Comment by shezdy** [comment]
try 7848e36f10e914185d14ad38faded994fe41a4a3

i won't have access to my computer for a few more days to actually test, but that should commit work.
