### ISSUE TITLE
hyprsplit on nixpkgs

### ISSUE THREAD

**Issue by luiswirth** [shezdy/hyprsplit#16]
It would be great to have this plugin on nixpkgs, just like hy3.

The current standalone flake situation forces me to also use the hyprland flake, instead of enabling me to use the hyprland from nixpkgs...

**Comment by nonetrix** [comment]
That would be great, I don't mind testing for Vaxry but at same time just stable version I could use would be great

**Comment by shezdy** [comment]
> stable version I could use would be great

I think you can already use a tagged version by setting the url for both hyprland and the plugin. eg `hyprland.url = "git+https://github.com/hyprwm/Hyprland?submodules=1&ref=v0.41.1";` and `hyprsplit.url = github:shezdy/hyprsplit&ref=v0.41.1;`. my syntax might be wrong, i haven't used nix recently.

**Comment by MOIS3Y** [comment]
Today I saw this [PR](https://github.com/NixOS/nixpkgs/pull/342075), if it is accepted, it will be great
