### ISSUE TITLE
Different number of workspaces for each monitor?

### ISSUE THREAD

**Issue by saipavanc** [shezdy/hyprsplit#19]
Hi, I have been experiencing issues with split-monitorworkspaces (I will refer to this as spw) as well. Specifically the following, I was looking for a dispatcher for `prev` which works well, when trying to go to the old used workspace in the current monitor. spw fails to do that. I hope that is fixed, I will just give this a try once I will get to my dual monitor setup.

Also, in my setup I usually have separate number of persistent workspaces on different monitors. Is it possible to have the `num_workspaces` setting for each monitor separately, maybe using the monitor name?

**Comment by shezdy** [comment]
> I was looking for a dispatcher for `prev` which works well, when trying to go to the old used workspace in the current monitor. spw fails to do that. I hope that is fixed, I will just give this a try once I will get to my dual monitor setup.

Going to the previous workspace already works with and without the plugin's dispatchers. Hyprland tracks the previous workspace on each monitor.

> Also, in my setup I usually have separate number of persistent workspaces on different monitors. Is it possible to have the `num_workspaces` setting for each monitor separately, maybe using the monitor name?

I'm not sure I understand why you want to do this? You don't need to use every workspace if you don't want to

**Comment by saipavanc** [comment]
> Going to the previous workspace already works with and without the plugin's dispatchers. Hyprland tracks the previous workspace on each monitor.

Oh, this definitely did not work for me. I used the following: `bind = Super, Tab, split:workspace, prev`, and it does not stay in the same monitor. 

> I'm not sure I understand why you want to do this? You don't need to use every workspace if you don't want to

In my workflow, I like to keep a fixed number of workspaces, so I use persistent workspaces. If that is the case, I will have different number of workspaces on each monitor.

**Comment by shezdy** [comment]
previous workspace selection should be fixed in https://github.com/shezdy/hyprsplit/commit/d02a61319d515251a34db76f9506aea8b3916d0f, i didn't realize it could break depending on the dispatchers used

**Comment by shezdy** [comment]
> In my workflow, I like to keep a fixed number of workspaces, so I use persistent workspaces. If that is the case, I will have different number of workspaces on each monitor.


If you want to use persistent workspaces with different number per monitor can you not do something like this?
```
plugin:hyprsplit:num_workspaces = 6

workspace = 1, monitor:DP-1, persistent:true
workspace = 2, monitor:DP-1, persistent:true
workspace = 3, monitor:DP-1, persistent:true
workspace = 4, monitor:DP-1, persistent:true
workspace = 5, monitor:DP-1, persistent:true
workspace = 6, monitor:DP-1, persistent:true

workspace = 7, monitor:DP-2, persistent:true
workspace = 8, monitor:DP-2, persistent:true

workspace = 13, monitor:HDMI-A-1, persistent:true
workspace = 14, monitor:HDMI-A-1, persistent:true
workspace = 15, monitor:HDMI-A-1, persistent:true
```
