### ISSUE TITLE
[Feature Request] Monitor Independent navigation

### ISSUE THREAD

**Issue by hiddenruins** [shezdy/hyprsplit#20]
Hi there, thanks for such an awesome plugin.

One of the main features i've been missing from awesome WM is monitor independent navigation. In Hyprland, all the navigation dispatchers such as movefocus, prev, etc are shared between monitors. 

If I'm on Monitor A, when I do Mod + L (bind = $mainMod, h, movefocus, l), the focus goes to Monitor B.
When I do Prev Workspace (bind = $mainMod, ESCAPE, workspace, previous -     binds:allow_workspace_cycles = true), it goes back and forth across monitors instead of in the same monitor.
Same behaviour with all other dispatchers. 

Currently I'm using simple bash script for going back and forth workspaces in the same monitor. But It would be great to have monitor independent features built in to a plugin.

**Comment by shezdy** [comment]
I think moving focus with direction on the same monitor is a reasonable feature request for Hyprland itself

As for going to the previous workspace on the same monitor try with `bind = $mainMod, ESCAPE, split:workspace, previous`

**Comment by hiddenruins** [comment]
Not sure i'm i'm doing something wrong but `bind = $mainMod, ESCAPE, split:workspace, previous`  didn't work for me. The behavior is the same as `workspace`

**Comment by shezdy** [comment]
Hyprland version? You need to be be on -git for it to work.

**Comment by hiddenruins** [comment]
Oh, I'm on the stable right now. Thanks for the head up. I'll test on -git and report back.
